#
# Thino Package configuration file
# More info at http://keypirinha.com
#

[common]
# メモ前の空行を保証するか
# Whether to ensure a blank line before memo.
# * Default: no
# ensure_blank_line_before_memo = no

[main]
enabled = yes

# カタログでの表示名
# The display name of the default item.
# * Default: Thino:
# item_label = Thino:

# メモを追記する Vault 名
# Target obsidian vault name.
# * Default: Memos
# vault_name = Memos

# 追記するメモの書式
# Pythonのstrftime構文（例: %y/%m/%d %H:%M:%S）、および {MEMO} 置換ホルダーをサポートします
# 波括弧をそのまま出力したい場合は {{}} のように二重波括弧を使用します
# Memo format, supports Python strftime syntax (ex: %y/%m/%d %H:%M:%S) and {MEMO} replaceholder.
# Use double braces like {{}} when you want to output braces literally.
# * Default: %H:%M:%S {MEMO}
# memo_format = %H:%M:%S {MEMO}

# @WARN: Not supported.
# 特定のヘッダーの下に追記する場合のヘッダー（未指定の場合はファイルの末尾に追加）
# Target heading for appending memo (if not specified, append to EOF).
# * Default:
# target_heading =

# メモ後に改行を追加するか
# Whether to append a newline after memo.
# * Default: yes
# append_newline_after_memo = yes

# [custom/*]
# メインとは別に任意の設定の項目を複数追加出来ます
# In addition to the main item, it is possible to define one or several extra
# items to insert into the Catalog, with different main setting.

# Examples:
# [custom/example]
# enabled = yes
# item_label = Thino: Example
# vault_name = Example
# memo_format = "%H:%M {{#Memo}} {MEMO}"
# Not supported
# target_heading = "## Memos"
# append_newline_after_memo = yes

[var]
# As in every Keypirinha's configuration file, you may optionally include a
# [var] section to declare variables that you want to reuse anywhere else in
# this file.
#
# Note that the [var] section is inherited, which means that any value defined
# in the main configuration file of the application (i.e.: "Keypirinha.ini") has
# already been made available to this file as well so you do not need to
# duplicate it here unless you want to override it.
#
# REMINDER: For convenience, Keypirinha silently populates this section with
# predefined values that may come handy. Here are some of them: APP_DIR,
# APP_EXE, PROFILE_DIR, PROFILE_DIR_INSTALLED_PACKS, PROFILE_DIR_LIVE_PACKS,
# PROFILE_DIR_USER and the KNOWNFOLDER_* and KNOWNFOLDERGUID_* values.
#
# See the "Configuration" chapter of the documentation for more information.


[env]
# For convenience, Keypirinha populates this [env] section in every loaded
# configuration file so you can easily access to environment variables like
# PATH for example from this file using syntax: ${env:PATH}
#
# If an environment variable happens to be changed while Keypirinha is running
# and this modification impacts current configuration, application and packages
# configuration will be reloaded if needed only.
#
# See the "Configuration" chapter of the documentation for more information.
